framework:
    secret: '%env(APP_SECRET)%'
    form: true
    csrf_protection: true
    templating: { engines: ["twig"] }
    session:
        handler_id: ~
    serializer:
        mapping:
            paths:
                - '%kernel.project_dir%/config/serialization'
